# docker-compose.yml
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "4000:4000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge