name: CI and Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose up --build --abort-on-container-exit

    - name: Copy coverage reports
      run: |
        mkdir -p ./coverage/api
        mkdir -p ./coverage/client
        cp -r ./coverage/api ./coverage/client ./

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: |
          ./coverage/api/lcov.info
          ./coverage/client/lcov.info
        flags: |
          api
          client
