name: CI and Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        run: |
          docker compose up --build --abort-on-container-exit

      - name: Copy coverage reports
        run: |
          mkdir -p ./coverage/api
          mkdir -p ./coverage/client
          docker cp api:/path/to/coverage/lcov.info ./coverage/api/lcov.info
          docker cp client:/path/to/coverage/lcov.info ./coverage/client/lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            ./coverage/api/lcov.info
            ./coverage/client/lcov.info
          flags: |
            api
            client
